# Generated by Django 4.2.5 on 2023-10-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(default='hdfd', max_length=2000),
        ),
    ]
